version: "3.7"
services:
  app:
    build:
      context: .
      target: app
    image: docker-ui
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10000:10000"